apiVersion: apps/v1
kind: Deployment
metadata:
    name: vue
    labels:
        app: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
            - name: vue
              image: anandpatnaik/myproject:vue-test-v1
              ports:
              - containerPort: 80
